name: go-test

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Cache node modules
        uses: actions/cache@v2
        id: node_cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node2-
      - name: list
        run: ls -l
      - name: ok
        run: npx firebase
      - name: Run test
        if: steps.node_cache.outputs.cache-hit != 'true'
        run: npm ci

