name: go-test

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run test
        run: make test
