name: go-test

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node1-
      - name: Run test
        run: firebase
      - name: Run test
        run: npm ci
