name: Pull request test
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  pull_request_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: pip
        run: pip install PyGithub
      - name: Run test
        run: python pull_req.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
