name: Python test

on:
  push:
    # paths:
    #   - ./**/*.py

jobs:
  build:
    strategy:
      matrix:
        python: ['3.6']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    name: Python ${{ matrix.python }} test ( ${{ matrix.os }} )
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install poetry
        run: pip install poetry
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ matrix.os }}-poetry-${{ matrix.python }}-${{ hashFiles('./poetry.lock') }}
      - name: poetry config list
        run: poetry config --list
