name: Python test

on:
  push:
    # paths:
    #   - ./**/*.py

jobs:
  build:
    strategy:
      matrix:
        python: ['3.6']
        name: ['echo']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    name: Python ${{ matrix.python }} test ( ${{ matrix.os }} )
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-poetry@v1
          restore-keys: |
            ${{ runner.os }}-pip-poetry
      - name: Install poetry
        run: pip install poetry
      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ matrix.os }}-poetry-.venv-${{ matrix.python }}-${{ hashFiles('./poetry.lock') }}
      - name: poetry config list
        run: poetry config --list

      - name: install package
        run: poetry install

      - name: test ${{ matrix.name }}
        run: echo 'test da "aa ${{ matrix.name }}"'

      - name: test command
        run: ${{ matrix.name }} "test"
