name: Release Draft

on:
  push:
    branches:
      - master

jobs:
  draft_release:
    runs-on: self-hosted
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: master
