name: Release Draft

on:
  push:
    tags:
      - v*.*.*

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
