name: Release Draft

on:
  push:
    branches:
      - feature/*

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: deresmos/release-drafter@feature/test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
