name: "WIP"

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - edited
      - reopened
jobs:
  wip:
    runs-on: ubuntu-latest
    name: check wip
    steps:
      - uses: deresmos/wip-action@feature/wip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
